/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf9f4",
        "secondary-fixed": "#ffdea6",
        "on-tertiary-fixed-variant": "#474746",
        "tertiary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#30312e",
        "surface-container": "#f0eee9",
        "on-surface-variant": "#554240",
        "error-container": "#ffdad6",
        "secondary": "#7b5800",
        "surface-tint": "#9d4139",
        "on-tertiary-fixed": "#1c1b1b",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#5d4200",
        "surface-container-low": "#f5f3ee",
        "surface-dim": "#dbdad5",
        "outline": "#89726f",
        "tertiary": "#0a0a0a",
        "primary": "#210000",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#7e2b23",
        "primary-fixed": "#ffdad5",
        "inverse-primary": "#ffb4aa",
        "surface-container-high": "#eae8e3",
        "outline-variant": "#dcc0bd",
        "on-tertiary": "#ffffff",
        "on-surface": "#1b1c19",
        "on-secondary": "#ffffff",
        "tertiary-container": "#212121",
        "on-background": "#1b1c19",
        "surface": "#fbf9f4",
        "secondary-fixed-dim": "#f7bd48",
        "primary-container": "#4a0404",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#271900",
        "background": "#fbf9f4",
        "primary-fixed-dim": "#ffb4aa",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "on-secondary-container": "#715000",
        "inverse-on-surface": "#f2f1ec",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-container": "#8a8888",
        "on-primary-container": "#d26a5f",
        "on-error": "#ffffff",
        "secondary-container": "#fdc34d",
        "on-primary-fixed": "#410001",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        'headline': ['"Noto Serif"', 'serif'],
        'body': ['"Work Sans"', 'sans-serif'],
        'label': ['"Work Sans"', 'sans-serif']
      },
      transitionTimingFunction: {
        'monu-ease': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
      }
    },
  },
  plugins: [],
}
